### ISSUE TITLE
Enny grace contribution

### ISSUE THREAD

**Issue by Bright4foi** [zuri-training/Proj_debtors_34#35]

**Comment by EnnyGrace** [comment]
1. I worked the Text styles
https://www.figma.com/file/GGGwipSNujrUUDM3t81xxD/Zuri-Project_Team-34-(My_Debtors)?node-id=135%3A20

2. I worked on the lofi of Forgot password, Register and Terms and Condition pages
https://www.figma.com/file/GGGwipSNujrUUDM3t81xxD/Zuri-Project_Team-34-(My_Debtors)?node-id=1095%3A369
https://www.figma.com/file/GGGwipSNujrUUDM3t81xxD/Zuri-Project_Team-34-(My_Debtors)?node-id=1098%3A289
https://www.figma.com/file/GGGwipSNujrUUDM3t81xxD/Zuri-Project_Team-34-(My_Debtors)?node-id=1098%3A623

3. I worked on the mobile view of Terms and Condition Page
https://www.figma.com/file/GGGwipSNujrUUDM3t81xxD/Zuri-Project_Team-34-(My_Debtors)?node-id=2457%3A10345
